Fix #3159. src and dst jupyterhub db root may be the same.
radiasoft/sirepo pull request #3160
Opened 2020-11-20 16:38 UTC by e-carlin

In the case of the src and dst db root being the same we need to add another
check of the directories to make sure a new username doesn't conflict.

2020-11-20 21:17 UTC, robnagler requested changes
Simplify a bit and provide better chance on uniqueness test.

2020-11-20 21:17 UTC, robnagler commented on sirepo/sim_api/jupyterhublogin.py
> +        if u or pkio.sorted_glob(_user_dir(n)):
`_user_dir(n).exists()`

2020-11-20 21:17 UTC, robnagler commented on sirepo/sim_api/jupyterhublogin.py
> +        assert not pkio.sorted_glob(_user_dir(n)), \
`_user_dir(n).exists()`

2020-11-20 21:17 UTC, robnagler commented on sirepo/sim_api/jupyterhublogin.py
>              n += _HUB_USER_SEP + random.choice(string.ascii_lowercase)
`sirepo.util.random_base62(3).lower()` -- gives a better shot at uniqueness.

2020-11-20 21:17 UTC, robnagler commented on sirepo/sim_api/jupyterhublogin.py
> +            f'conflict with existing username={n}'
f'conflict with existing user_dir={n}'

2020-11-20 23:29 UTC, e-carlin commented on sirepo/sim_api/jupyterhublogin.py
> +        if u or pkio.sorted_glob(_user_dir(n)):
69b0fa64

2020-11-20 23:29 UTC, e-carlin commented on sirepo/sim_api/jupyterhublogin.py
>              n += _HUB_USER_SEP + random.choice(string.ascii_lowercase)
69b0fa64

2020-11-20 23:29 UTC, e-carlin commented on sirepo/sim_api/jupyterhublogin.py
> +            f'conflict with existing username={n}'
69b0fa64

2020-11-20 23:29 UTC, e-carlin commented on sirepo/sim_api/jupyterhublogin.py
> +        assert not pkio.sorted_glob(_user_dir(n)), \
69b0fa64

2020-11-23 16:42 UTC, robnagler approved these changes

2020-11-23 16:42 UTC, merged