FLASH on NERSC
radiasoft/sirepo pull request #4031
Opened 2021-12-31 19:56 UTC by e-carlin

- Use output of prepare_simulation to start  codes through sbatch with the proper command
- Get FLASH running on NERSC

2021-12-31 23:10 UTC, robnagler requested changes
Looks good. Only minor comments.

2021-12-31 23:10 UTC, robnagler commented on sirepo/pkcli/job_agent.py
> -#TODO(robnagler) need to get command from prepare_simulation
yay!

2022-01-03 17:51 UTC, e-carlin commented on sirepo/feature_config.py
> +        in_slurm=(False, bool, 'True if being run by slurm'),
810919fd5

2022-01-03 17:51 UTC, e-carlin commented on sirepo/mpi.py
> +    m = [
810919fd5

2022-01-03 17:51 UTC, e-carlin commented on sirepo/pkcli/job_agent.py
> +        e = PKDict(SIREPO_FEATURE_CONFIG_IN_SLURM=1)
810919fd5

2022-01-03 17:56 UTC, e-carlin commented on sirepo/package_data/static/json/flash-schema.json
> +            "sbatchCores": ["Cores", "Integer", 128],
It is. I don't think there is a way to share it currently. Do you have any suggestions?

One thought that has been roaming around my head is wondering if we should build more structure around schemas so we can treat them more as code and less as json. I've been thinking about this wrt the class stuff Mike has been adding and this case seems like another area where we would benefit.

2022-01-03 17:58 UTC, e-carlin commented
@robnagler ready for another review.

2022-01-04 16:08 UTC, robnagler approved these changes

2022-01-04 16:59 UTC, merged