Fix #3810: flask messages
radiasoft/sirepo pull request #4354
Opened 2022-04-20 22:23 UTC by gurhar1133

Now logs message when server is true

2022-04-21 14:58 UTC, robnagler requested changes
I wrote comments about comments. Let me know if you don't understand why I made those changes.

2022-04-21 14:58 UTC, robnagler commented on sirepo/util.py
> +#: Treat as read only. Only set by server.py
`#: This should be treated as read only and used sparingly. See discussion in sirepo.server.init`

2022-04-21 14:58 UTC, robnagler commented on sirepo/util.py
> +                pkdlog('flask.request is False')
`# This will help debug https://github.com/radiasoft/sirepo/issues/3727`

2022-04-21 14:58 UTC, robnagler commented on sirepo/server.py
> +        # giving this info to util so it knows to show message
`# Currently used for a special case in sirepo.util.in_flask_request. Do not use widely, because we should avoid server vs pkcli dependencies.`

2022-04-21 15:43 UTC, gurhar1133 commented
Made changes

@robnagler, some of your comments have ':' and some don't. What is the rule pertaining to ':' again? 

Otherwise the changes to comments make sense

2022-04-22 00:58 UTC, robnagler commented
Here's the example: https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html

It's a way to get the string into the generated documentation.

2022-04-22 00:58 UTC, robnagler approved these changes

2022-04-22 00:58 UTC, merged