Fix #4072: jupyterhub slack link
radiasoft/sirepo pull request #4369
Opened 2022-04-26 17:52 UTC by gurhar1133

* There is now a slack icon link in jupyterhub on development jupyterhub
* The next steps will involve making changes to rsconf/.../conf.py.jinja for production
Thoughts @robnagler @e-carlin

2022-04-26 23:25 UTC, robnagler requested changes

2022-04-26 23:25 UTC, robnagler commented on sirepo/package_data/jupyterhub_templates/page.html
> +    const slackUri = SIREPO.authState.slackUri;
No need for temporary variable.

2022-04-26 23:25 UTC, robnagler commented on sirepo/package_data/jupyterhub_templates/page.html
> +<script src="/auth-state">
Put a jinja comment `{# #}` with a POSIT for where this is defined. Unfortunately, you can't put comments in JSON so you can't POSIT in schema-common.json.

2022-04-27 15:56 UTC, e-carlin commented on sirepo/jupyterhub.py
> +import pykern.pkresource
sort

2022-04-27 15:56 UTC, e-carlin commented on sirepo/package_data/jupyterhub_templates/page.html
> +    <a id="sirepo-slack-link" href="https://slack.sirepo.com">
We use 2 space indent in html

2022-04-27 16:05 UTC, gurhar1133 commented
Changes made

2022-04-27 19:57 UTC, robnagler approved these changes

2022-04-27 19:57 UTC, merged