Fix #4532: radia 3d axes update
radiasoft/sirepo pull request #4576
Opened 2022-07-05 18:38 UTC by gurhar1133

Binding the listeners to the sim view seems to have fixed to issue.

@mkeilman while working on this I noticed a potential bug (on my branch and master). If you move the 3d element around a lot and then try to quickly click on the simulations link you may run into the js error:
```
 Cannot read properties of undefined (reading '0')
```
or 
```
 Cannot read properties of undefined (reading '1')
```
I think this has to do with the coords calculations for `lCoord` still being in progress 
```javascript
viewPortPoint(worldPoint) {
        // this is required to do conversions for different displays/devices
        const pixels = window.devicePixelRatio;
        this.worldCoord.setCoordinateSystemToWorld();
        this.worldCoord.setValue(worldPoint.coords());
        const lCoord = this.worldCoord.getComputedLocalDisplayValue()
            .map(x => x / pixels);
        return new SIREPO.GEOMETRY.Point(lCoord[0], lCoord[1]);
    }
```

Should I open an issue for this?

2022-07-05 19:23 UTC, mkeilman commented
Yes, go ahead and open an issue. I wonder if it's object destruction vs. debounce delay...

2022-07-05 19:37 UTC, mkeilman commented
Zoom does not update the axes. I think that handler (`onwheel`) needs to stay on the render window

2022-07-05 20:09 UTC, mkeilman requested changes
See my comment about the zoom handler

2022-07-05 21:09 UTC, gurhar1133 commented
@mkeilman I think it's fixed now. LMK if anything else 👍

2022-07-05 21:13 UTC, mkeilman approved these changes
Works well!

2022-07-07 16:29 UTC, mkeilman commented
> @mkeilman can we merge this one? Paul says if you approve he does too.

Yep!

2022-07-07 16:33 UTC, merged