Fix #3739: field lineout animation for parallel field calculations
radiasoft/sirepo pull request #4796
Opened 2022-09-06 16:50 UTC by gurhar1133

* Field Lineout Report changed to an animation so that we can run these calculations parallel with MPI
* A UI quirk @moellep wanted me to mention: The progress bar for the fieldLineoutAnimation appears to get triggered by the kickmap report when running the solver
* not sure if doing things 100% correctly in `_compute_model()` in `sim_data/radia.py`

2022-09-07 17:46 UTC, mkeilman requested changes
See comments

2022-09-07 17:46 UTC, mkeilman commented on sirepo/package_data/static/js/radia.js
> +                </div>
I think you want a full simStatusPanel here, since we will want to run on nersc, select number of cores, etc.

2022-09-07 17:46 UTC, mkeilman commented on sirepo/package_data/static/json/radia-schema.json
> +        },
Add the fields for parallel execution (copy from `solverAnimation`)

2022-09-07 17:46 UTC, mkeilman commented on sirepo/package_data/template/radia/examples/undulator.json
> +        "fieldLineoutAnimation": {
Do the same to the other examples (dipole and wiggler)

2022-09-07 19:05 UTC, gurhar1133 commented on sirepo/package_data/template/radia/fieldLineoutAnimation.py.jinja
> +    return radia.generate_field_data('{{ sim_id }}', radia.get_g_id(), '{{ name }}','{{ f_type }}', [PKDict({{ f_path }})]).data[0].vectors
I'm not sure how we avoid importing the template given that we need to parallelize the call to radia.generate_field_data()

2022-09-07 19:05 UTC, gurhar1133 commented on sirepo/package_data/static/json/radia-schema.json
> -        "fieldLineoutReport": {
Not sure I follow you here, I deleted fieldLineoutReport and replaced with fieldLineoutAnimation in radia-schema.json

2022-09-07 20:12 UTC, mkeilman commented on sirepo/package_data/static/json/radia-schema.json
> -        "fieldLineoutReport": {
This is in the `constants.dataDownloads` section

2022-09-07 20:16 UTC, mkeilman commented on sirepo/package_data/template/radia/fieldLineoutAnimation.py.jinja
> +    return radia.generate_field_data('{{ sim_id }}', radia.get_g_id(), '{{ name }}','{{ f_type }}', [PKDict({{ f_path }})]).data[0].vectors
You'd have to build the text of the function, which would call `radia_util.get_field()`, I think. It was more a rumination than anything, so you can ignore it for this pr

2022-09-07 20:44 UTC, gurhar1133 commented on sirepo/package_data/static/json/radia-schema.json
> -        "fieldLineoutReport": {
gotcha 👍

2022-09-09 13:55 UTC, mkeilman approved these changes
Looks good!

2022-09-09 14:11 UTC, e-carlin requested changes
LGTM. Few nits. 

 There should probably be a fixup to delete all old fieldLineoutReport models.

Also, I still see mentions of the report  in the code
```txt
sirepo (3739-field-lineout-animation)$ g fieldlineoutreport
./package_data/static/js/radia.js:1724:                    '<model>': 'fieldLineoutReport',
./template/radia.py:82:_POST_SIM_REPORTS = ["fieldIntegralReport", "fieldLineoutReport", "kickMapReport"]
./template/radia.py:86:    "fieldLineoutReport",
./template/radia.py:175:    if sim_in.report == "fieldLineoutReport":
./template/radia.py:180:                sim_in.models.fieldLineoutReport.fieldType,
./template/radia.py:181:                sim_in.models.fieldLineoutReport.fieldPath,
./template/radia.py:182:                sim_in.models.fieldLineoutReport.plotAxis,
./template/radia.py:213:    if model == "fieldLineoutReport":
```

2022-09-09 14:11 UTC, e-carlin commented on sirepo/package_data/static/js/radia.js
> +                if (! $scope.dataCleared && $scope.hasPaths()) {
Make `! $scope.dataCleared && $scope.hasPaths()` into a named function so it is clear what it is testing for and use it here and in the template above. Also, all of these ifs can be collapsed into one.

2022-09-09 14:11 UTC, e-carlin commented on sirepo/sim_data/radia.py
>          if analysis_model in ("solverAnimation", "reset"):
elif

2022-09-09 14:11 UTC, e-carlin commented on sirepo/template/radia.py
> +        if not field_data
Better to reverse these and get rid of the `not`

2022-09-09 18:02 UTC, gurhar1133 commented
Made the changes @e-carlin

2022-09-09 19:55 UTC, e-carlin approved these changes

2022-09-09 23:04 UTC, merged