Fix #4850: analysis jobs now have run_dir arg
radiasoft/sirepo pull request #4898
Opened 2022-09-29 20:41 UTC by gurhar1133

Calls to simulation_db.simulation_run_dir have been removed and now analysis jobs take a run_dir arg.
Analysis jobs now take **kwargs.

2022-09-29 23:07 UTC, robnagler requested changes

2022-09-29 23:07 UTC, robnagler commented on sirepo/template/template_common.py
> +from sirepo import simulation_db
This import should be localized in analysis_job_dispatch. There are circular import issues here.

2022-09-29 23:07 UTC, robnagler commented on sirepo/template/template_common.py
> +    d = simulation_db.simulation_run_dir(
Passing data should work. parse_model looks for computeModel so you don't need this extra pkdict.

2022-09-29 23:07 UTC, robnagler commented on sirepo/template/template_common.py
> +    )(data, d)
temporary variable is unnecessary since it is only used once.

2022-09-30 16:50 UTC, gurhar1133 commented
@robnagler should be fixed now

2022-09-30 20:34 UTC, robnagler approved these changes

2022-09-30 20:35 UTC, merged