Fix #4191 make websockets work in angular in parallel with http
radiasoft/sirepo pull request #6092
Opened 2023-07-10 18:12 UTC by robnagler

2023-07-18 16:21 UTC, e-carlin requested changes
Code all looks good. The browser seems to be faster \<snap\>. 

I noticed a few issues. Not positive they are related to this work:
1. srw -> light source facilities -> nsls2 -> nsls2 esm beam line -> nsls2 elm beam line -> coherent results
```
sirepo/job_driver/__init__.py:306:_receive LocalDriver(a=k5Ek k=sequential u=Ir6N [_Op(analysis, DcBO)]) error msg={'agentId': 'k5EksGpsROcOy0zQGc0Qh6F43lBwJFyF', 'opId': 'DcBOhnM0nB7ek48csrWybOJ10RmhO5U5', 'opName': 'analysis', 'reply': {'error': 'report not generated', 'stack': 'Traceback (most re\
cent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 252, in _do_get_simulation_frame
    return template_common.sim_frame_dispatch(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 705, in sim_frame_dispatch
    res = o(frame_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 507, in sim_frame
    m = _copy_frame_args_into_model(frame_args, "watchpointReport")
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 483, in _copy_frame_args_into_model
    m[f] = float(m[f])
ValueError: could not convert string to float: '1e%2B30'
```
2. Url for Jupyter aren't correct (ex http://localhost/jupyterhublogin instead of http://127.0.0.1:8080/jupyterhublogin). This is when running with etc/run-jupyterhub.sh
3. srw esm beamline when I clicked on "Open as new shadow simulation" and then clicked on the provided link
```
angular.js:15567 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at iconUrl (sirepo-beamline.js?20230718.161240:480:26)
    at controller (sirepo-beamline.js?20230718.161240:505:30)
    at Object.invoke (angular.js:5141:16)
    at S.instance (angular.js:11704:24)
    at p (angular.js:10517:33)
    at g (angular.js:9832:13)
    at g (angular.js:9835:13)
    at p (angular.js:10579:11)
    at g (angular.js:9832:13)
    at g (angular.js:9835:13)
```

2023-07-18 16:21 UTC, e-carlin commented on sirepo/uri_router.py
> +                pkdlog("uri={} {}; route={} kwargs={} ", c.uri, e, r, k)
Maybe add a pkdc controlled dump of the full message contents? I frequently use the network tab in the browser to see what payloads are going back and forth which no longer works with ws.

2023-07-18 16:21 UTC, e-carlin commented on sirepo/request.py
> +            #            http_request_uri="/",
odd formatting?

2023-07-22 23:43 UTC, robnagler commented
- working end-to-end with limited browser testing
- half-integrated msgpack (binary messages) which was necessary to get srw image sample preview working
- unit tests use websockets like the browser (if feature_config.ui_websocket enabled)
- auth still occurs through http
- http prefix is still not coded, but not necessary for most functions (just jupyter)

Next:
- http prefix
- msgpack for requests
- use msgpack, not json for dict reply/request

2023-08-22 15:34 UTC, robnagler commented
@e-carlin this is ready for another review. I think it could be merged (only on in dev). The next big issues are caching frames and pub/sub for runStatus. These should be separate concerns. The former is necessary for a prod release but not the latter.

One question I have is how frequently should the UI try restarts on the websocket. I think polling is fine, since it's a lightweight request. There might need to be a user alert in the UI that connection has been interrupted from more than, say, 30 seconds (server restart).

2023-08-25 20:58 UTC, e-carlin approved these changes
Only one small comment on a comment.

All of my click around testing worked. Obviously there are counltess cases I didn't manually test so it would be good for other people to click around edge cases in their apps.

One general comment, I find myself frequently opening the developer tools network tab to view what requests are made and what the content of those requests are. With websockets and a binary protocol that now doesn't work. What about adding a pkdc to parse_message and websocket_response that allows one to dump the message (with associated uri, seq num, etc)?

2023-08-26 19:30 UTC, robnagler commented on sirepo/package_data/static/js/sirepo.js
> +        // close: event.code : short, event.reason : str, wasClean : bool
These are standard codes in JS: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close_event

2023-08-26 19:33 UTC, robnagler commented on sirepo/package_data/static/js/sirepo.js
> +    const _isAuthenticated = () =>  {
Fixed

2023-08-26 19:49 UTC, robnagler commented
https://github.com/radiasoft/sirepo/issues/6250

2023-08-26 20:16 UTC, merged