fix #6273 fix autoSave error cases
radiasoft/sirepo pull request #6347
Opened 2023-09-25 23:14 UTC by moellep

- remove uncalled errorCallback from autoSave()
 - fixed bug if resp.error is present in autoSave response, but error is not invalidSerial
 - update fileManager sim from server response when renaming
 - if an invalidSerial occurs on the server, return the on-disk simulation data to be refreshed on the client

2023-09-26 17:24 UTC, robnagler requested changes

2023-09-26 17:24 UTC, robnagler commented on sirepo/package_data/static/js/sirepo.js
> +                            if (resp.error === 'invalidSerial') {
I fixed the code in #6300 to remove this test here, and instead to [refresh the app](https://github.com/radiasoft/sirepo/pull/6300/files#diff-c1af31ef028c0a9ee6c6e71acb4b0ad646d4136dd06d3a1bc9cdb11c55fbc801R588). It never happens, and when it does, a complete refresh is probably safest given the amount of caching in the app and the fact that simulationData was never used.

Your new code (after #6300 is merged shortly) should simply remove the errorCallback. Easiest thing would be revert this change in your branch so you don't get a conflict.

2023-09-26 17:24 UTC, robnagler commented on sirepo/simulation_db.py
> -                simulationData=data,
Remove this to avoid conflict with #6300.

2023-09-26 21:08 UTC, moellep commented
OK - I've changed this PR to a draft and will look at it again after #6300

2023-09-26 21:43 UTC, robnagler commented
#6300 has been merged.

2023-09-28 17:01 UTC, moellep commented
Closing this, will open a new PR.

2023-09-28 17:01 UTC, closed without merging