Fix #6765 #6720 improve images
radiasoft/sirepo pull request #6785
Opened 2024-02-16 21:18 UTC by gurhar1133

2024-02-20 16:33 UTC, mkeilman commented
I'm currently getting a reshape error with the CIFAR-4 data:
```python
../sirepo/job_driver/__init__.py:279:_agent_receive LocalDriver(a=taLq k=sequential u=2Dzs [_Op(analysis, QR9X)]) error msg={'agentId': 'taLqX1rn6pcfKBuGICu6YPRU9IRmnKn6', 'opId': 'QR9XDULlN7Xf8cvgrn39tpFeridJFSlm', 'opName': 'analysis', 'reply': {'error': 'Invalid shape () for image data', 'stack': 'Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 119, in _dispatch_compute
    return _op(expect_file=x)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 97, in _op
    r = getattr(template_common, f"{msg.jobCmd}_dispatch")(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 738, in stateful_compute_dispatch
    return getattr(t, f"stateful_compute_{m}")(**k, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 376, in stateful_compute_sample_images
    return _ImagePreview(data).images()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1271, in images
    self._append_output_image(y, i)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1232, in _append_output_image
    self._gen_image()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1217, in _gen_image
    plt.imshow(self.currentImage)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2695, in imshow
    __ret = gca().imshow(
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5663, in imshow
    im.set_data(X)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/image.py", line 710, in set_data
    raise TypeError("Invalid shape {} for image data"
TypeError: Invalid shape () for image data
```

2024-02-20 17:14 UTC, gurhar1133 commented
> I'm currently getting a reshape error with the CIFAR-4 data:
> 
> ```python
> ../sirepo/job_driver/__init__.py:279:_agent_receive LocalDriver(a=taLq k=sequential u=2Dzs [_Op(analysis, QR9X)]) error msg={'agentId': 'taLqX1rn6pcfKBuGICu6YPRU9IRmnKn6', 'opId': 'QR9XDULlN7Xf8cvgrn39tpFeridJFSlm', 'opName': 'analysis', 'reply': {'error': 'Invalid shape () for image data', 'stack': 'Traceback (most recent call last):
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 119, in _dispatch_compute
>     return _op(expect_file=x)
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 97, in _op
>     r = getattr(template_common, f"{msg.jobCmd}_dispatch")(
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 738, in stateful_compute_dispatch
>     return getattr(t, f"stateful_compute_{m}")(**k, **kwargs)
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 376, in stateful_compute_sample_images
>     return _ImagePreview(data).images()
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1271, in images
>     self._append_output_image(y, i)
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1232, in _append_output_image
>     self._gen_image()
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1217, in _gen_image
>     plt.imshow(self.currentImage)
>   File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2695, in imshow
>     __ret = gca().imshow(
>   File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/__init__.py", line 1446, in inner
>     return func(ax, *map(sanitize_sequence, args), **kwargs)
>   File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5663, in imshow
>     im.set_data(X)
>   File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/matplotlib/image.py", line 710, in set_data
>     raise TypeError("Invalid shape {} for image data"
> TypeError: Invalid shape () for image data
> ```

sorry. I forgot about CIFAR. I'll fix

2024-02-20 18:49 UTC, gurhar1133 commented
@mkeilman try again?

2024-02-20 22:38 UTC, gurhar1133 commented
> New error for me:
> 
> ```
> ../sirepo/job_driver/__init__.py:279:_agent_receive LocalDriver(a=LNHj k=sequential u=2Dzs [_Op(analysis, AZer)]) error msg={'agentId': 'LNHjlTj14D3LNe7psqmthiZRVxVWD8iB', 'opId': 'AZermDobNBQ638rsQLV7AkOPbQ6O7Z0Q', 'opName': 'analysis', 'reply': {'error': 'Selection can't process b'bird'', 'stack': 'Traceback (most recent call last):
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 119, in _dispatch_compute
>     return _op(expect_file=x)
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 97, in _op
>     r = getattr(template_common, f"{msg.jobCmd}_dispatch")(
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 738, in stateful_compute_dispatch
>     return getattr(t, f"stateful_compute_{m}")(**k, **kwargs)
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 376, in stateful_compute_sample_images
>     return _ImagePreview(data).images()
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1280, in images
>     self._append_output_image(y, i)
>   File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/activait.py", line 1234, in _append_output_image
>     self.file[self.io.output.label_path][data[index]]
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 841, in __getitem__
>     selection = sel.select(self.shape, args, dataset=self)
>   File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
>     return selector.make_selection(args)
>   File "h5py/_selector.pyx", line 282, in h5py._selector.Selector.make_selection
>   File "h5py/_selector.pyx", line 181, in h5py._selector.Selector.apply_args
> TypeError: Selection can't process b'bird'
> ```
> 
> Probably `pkcompat.from_bytes()` needed somewhere?

I think output should be `metadata/image_types` not `metadata/labels`. Can you try  `metadata/image_types` as the output column? Maybe user needs a better message if wrong column selection doesn't work

2024-02-21 15:43 UTC, mkeilman commented
> I think output should be `metadata/image_types` not `metadata/labels`. Can you try `metadata/image_types` as the output column? Maybe user needs a better message if wrong column selection doesn't work

The problem is there's nothing to suggest that any column is somehow "correct" or "incorrect". If we know that ahead of time, then those columns should not be presented or the checkboxes disabled if the user should know the columns exist. If the only way to know is through an error, then yes a meaningful error would help. Do the shapes indicate which columns are compatible? Does it change for input vs output? Maybe some guidance from the experts is in order. I'd relegate all that to a new issue.

2024-02-21 17:20 UTC, gurhar1133 commented
> > I think output should be `metadata/image_types` not `metadata/labels`. Can you try `metadata/image_types` as the output column? Maybe user needs a better message if wrong column selection doesn't work
> 
> The problem is there's nothing to suggest that any column is somehow "correct" or "incorrect". If we know that ahead of time, then those columns should not be presented or the checkboxes disabled if the user should know the columns exist. If the only way to know is through an error, then yes a meaningful error would help. Do the shapes indicate which columns are compatible? Does it change for input vs output? Maybe some guidance from the experts is in order. I'd relegate all that to a new issue.

Agreed. I made an issue for it [6805](https://github.com/radiasoft/sirepo/issues/6805)

2024-02-21 17:20 UTC, mkeilman requested changes
Aside from minor style things, see the comment re image paging

2024-02-21 17:20 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
> +                page {{ imageIdx / imagesPerPage + 1 }} of {{ numPages }}
This page counting is not robust against changes in total number or images or images per page. e.g. change `$scope.imagesPerPage` to 4 ("Page 1 of 3.75"), click to go to the end ("Page 3.75 of 3.75") and then start decrementing - at "Page 0.75 of 3.75" you get a 404 error and a broken image.

2024-02-21 17:20 UTC, mkeilman commented on sirepo/template/activait.py
> +            y=self.outputs,
Can `x` and `y`  be made more descriptive? I'm not sure what they represent, especially on the javascript side where the context here is lost.

2024-02-21 17:47 UTC, gurhar1133 commented on sirepo/package_data/static/js/activait.js
> +            <div class="col-md-{{ hasThirdColumn ? '4' : '6' }}">
Not to my knowledge. We only have three columns if we are doing image to image

2024-02-26 16:44 UTC, mkeilman requested changes
Image paging works great.  Just a handful of items I noticed

2024-02-26 16:44 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
> +            };
I don't know where we landed re: "braceless" returns (here `const pageIndex = () => $scope.imageIdx / $scope.imagesPerPage;`) - but I advocate consistency within a directive at least. Though `canUpdateUri()` has a complex enough return value that I think it should use braces. Well, I leave it to you

2024-02-26 16:44 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
> +                        let value = column == 'A' ? `${$scope.colA[firstImageIndex + rowIndex].replace(/[\[\]]/g, '')}` : $scope.colB[firstImageIndex + rowIndex];
Can be `const`

2024-02-26 16:44 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
>          controller: function($scope, appState) {
Move `appState` to the directive function

2024-02-26 16:44 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
> +                    $(`.col${column}${$scope.method}${rowIndex + 1}`)[0].src = value;
Use a constant for the jquery selector. Also, restrict the selector to this element:
```javascript
const colSelector = $($element).find(`.col${column}${$scope.method}${rowIndex + 1}`)[0];
```

2024-02-26 16:44 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
> +                        $(`.pred${$scope.method}${rowIndex + 1}`)[0].src = $scope.pred[firstImageIndex + rowIndex];
As above, use a const and $element

2024-02-26 16:44 UTC, mkeilman commented on sirepo/package_data/static/js/activait.js
> +            $scope.ColBName = 'Contour';
`$scope.colAName` etc.

2024-02-26 18:23 UTC, gurhar1133 commented
@moellep ping

2024-02-26 18:39 UTC, mkeilman approved these changes

2024-02-28 22:02 UTC, merged