Fix #5568: rename cloudmc
radiasoft/sirepo pull request #6827
Opened 2024-02-29 18:39 UTC by gurhar1133

2024-02-29 21:11 UTC, gurhar1133 commented
once this is merged i can address: https://github.com/radiasoft/sirepo/pull/6824

2024-05-07 17:56 UTC, gurhar1133 commented on sirepo/feature_config.py
> +        openmc=dict(
@moellep what do you think?

2024-05-07 19:11 UTC, moellep commented on sirepo/feature_config.py
> +        openmc=dict(
Yes, we'll need this so people's cloudmc directory gets renamed.

2024-05-07 22:43 UTC, gurhar1133 commented
can you have a look @moellep please

2024-05-10 17:24 UTC, gurhar1133 commented
@moellep ping

2024-05-10 23:23 UTC, moellep commented on sirepo/db_upgrade.py
> +
This line is failing for me with an error ```AttributeError: 'API' object has no attribute 'cookie'```.

I was on the master branch, created some cloudmc simulations, then checked out this branch and started ```sirepo service http``` and it failed when it was looking up the simulation_dir() during the db upgrade.

2024-05-13 22:08 UTC, gurhar1133 commented
Another look @moellep think i fixed it

2024-05-14 16:26 UTC, moellep requested changes
I find my local simulations aren't getting copied over correctly. If I have a non-example simulation, and access /openmc after the upgrade has been run, I get this server error: 
```unsupported exception=<class 'AssertionError'> msg=invalid simulation type=cloudmc```

When I look at the simulation sirepo-data.json files in run/user/*/openmc, only the example files have the correct simulationType set to "openmc". The user simulations remain with simulationType "cloudmc".

To reproduce:
- open the master branch
- delete the entry in auth.db db_upgrade_t using sqlite
- open cloudmc and create a copy of the Aurora sim
- switch to the 5568-rename-cloudmc branch
- start the server and go to /openmc

2024-05-15 22:05 UTC, gurhar1133 commented
@moellep I think you have to un block to auto-merge

2024-05-15 23:05 UTC, moellep approved these changes

2024-05-15 23:05 UTC, merged