Fix #6863: slider cleanup
radiasoft/sirepo pull request #6888
Opened 2024-03-14 17:10 UTC by gurhar1133

2024-03-14 19:28 UTC, mkeilman requested changes
A couple of suggestions...

2024-03-14 19:28 UTC, mkeilman commented on sirepo/package_data/static/js/cloudmc.js
> +            sliderIndex: '=',
sliderIndex is not the best thing to use here; there are likely other conditions that may require hiding the labels. Something like hideMinMax is more flexible

2024-03-14 19:28 UTC, mkeilman commented on sirepo/package_data/static/js/cloudmc.js
> +            $scope.formatMinMax = val => {
We've decided on using parens around single parameters: `const formatFloat = (val) => {...}` etc.

2024-03-14 19:28 UTC, mkeilman commented on sirepo/package_data/static/js/cloudmc.js
>              };
More concise is
```
$scope.formatMinMax = (val) => $scope.hideMinMax ? '' : formatFloat(val);
```

2024-03-15 16:37 UTC, mkeilman approved these changes
One nitpick, then clear to merge.

2024-03-15 20:14 UTC, gurhar1133 commented
@moellep take a peak?

2024-03-15 21:38 UTC, moellep approved these changes

2024-03-15 21:38 UTC, merged