Fix #7074: impactt app
radiasoft/sirepo pull request #7081
Opened 2024-05-20 21:21 UTC by gurhar1133

2024-05-23 19:39 UTC, moellep requested changes

2024-05-23 19:39 UTC, moellep commented on sirepo/package_data/static/json/impactt-schema.json
> +        "BPM": {
Remove the BPM element and replace with a set of elements which have a negative ele_type from here. Just the common items for now, it doesn't have to include all of them.
https://github.com/ChristopherMayes/lume-impact/blob/master/impact/parsers.py#L400

For example, different models for OFFSET_BEAM (name, l, x_offset, y_offset, py_offset, z_offset, pzoffset), WRITE_BEAM (name, l, filename, sample_frequency)

2024-05-23 19:39 UTC, moellep commented on sirepo/package_data/static/json/impactt-schema.json
> +            "description": "A Dipole",
No need to have a "description" field here if it is just restating the name of the element displayed in the panel heading.

2024-05-29 22:01 UTC, gurhar1133 commented
@moellep ping

2024-05-30 18:10 UTC, moellep approved these changes
I made some changes with a76d2c6 - please give it a test and merge if it looks OK.
- Use RPNValue instead of Float in the schema
- Added default-data.json and a few changes to template.impactt so new sims can be created
- Updated the example to use the element positions from the lattice

2024-05-30 19:08 UTC, merged