fix #7380 replace slack link with support email
radiasoft/sirepo pull request #7401
Opened 2024-12-16 22:57 UTC by moellep

Consolidated support_email to a feature_config value.

2024-12-16 23:29 UTC, robnagler requested changes
Thanks for the thorough fix!

2024-12-16 23:29 UTC, robnagler commented on sirepo/feature_config.py
> +                "support@radiasoft.net",
support@sirepo.com

2024-12-16 23:54 UTC, moellep commented on sirepo/feature_config.py
> +                "support@radiasoft.net",
fixed with 958d651

2024-12-17 00:37 UTC, robnagler approved these changes

2024-12-17 00:38 UTC, merged